"""DNS handler for managing DNS configuration on FreeBSD."""

import os
import logging
from typing import List
from ..utils.system_utils import validate_ip_address


class DNSHandler:
    """
    Handles DNS configuration by managing /etc/resolv.conf.
    
    This class provides methods to read, add, remove, and update DNS servers
    in the system's resolv.conf file.
    """
    
    def __init__(self):
        """Initialize the DNSHandler."""
        self.logger = logging.getLogger(__name__)
        self.resolv_conf = "/etc/resolv.conf"
        self.backup_file = "/etc/resolv.conf.backup"
    
    def get_dns_servers(self) -> List[str]:
        """
        Read DNS servers from /etc/resolv.conf.
        
        Returns:
            List of DNS server IP addresses
        
        Example:
            >>> handler = DNSHandler()
            >>> servers = handler.get_dns_servers()
            ['8.8.8.8', '8.8.4.4']
        """
        dns_servers = []
        
        try:
            if not os.path.exists(self.resolv_conf):
                self.logger.warning(f"{self.resolv_conf} does not exist")
                return []
            
            with open(self.resolv_conf, 'r') as f:
                for line in f:
                    line = line.strip()
                    # Look for nameserver entries
                    if line.startswith('nameserver'):
                        parts = line.split()
                        if len(parts) >= 2:
                            dns_servers.append(parts[1])
            
            self.logger.info(f"Found {len(dns_servers)} DNS servers")
            return dns_servers
            
        except (IOError, PermissionError) as e:
            self.logger.error(f"Failed to read {self.resolv_conf}: {str(e)}")
            return []
    
    def set_dns_servers(self, servers: List[str]) -> bool:
        """
        Write DNS servers to /etc/resolv.conf.
        
        Args:
            servers: List of DNS server IP addresses
        
        Returns:
            True if successful, False otherwise
        
        Note:
            Backs up existing resolv.conf before making changes
        """
        try:
            # Validate all DNS server IPs
            for server in servers:
                if not self.validate_dns_ip(server):
                    self.logger.error(f"Invalid DNS server IP: {server}")
                    return False
            
            # Backup existing resolv.conf
            if os.path.exists(self.resolv_conf):
                try:
                    with open(self.resolv_conf, 'r') as src:
                        with open(self.backup_file, 'w') as dst:
                            dst.write(src.read())
                    self.logger.info(f"Backed up {self.resolv_conf} to {self.backup_file}")
                except Exception as e:
                    self.logger.warning(f"Failed to backup resolv.conf: {str(e)}")
            
            # Write new DNS configuration
            with open(self.resolv_conf, 'w') as f:
                f.write("# Generated by BSD Network Manager\n")
                for server in servers:
                    f.write(f"nameserver {server}\n")
            
            self.logger.info(f"Successfully wrote {len(servers)} DNS servers to {self.resolv_conf}")
            return True
            
        except (IOError, PermissionError) as e:
            self.logger.error(f"Failed to write {self.resolv_conf}: {str(e)}")
            return False
    
    def add_dns_server(self, server: str) -> bool:
        """
        Add a single DNS server to the configuration.
        
        Args:
            server: DNS server IP address
        
        Returns:
            True if successful, False otherwise
        """
        if not self.validate_dns_ip(server):
            self.logger.error(f"Invalid DNS server IP: {server}")
            return False
        
        # Get current servers
        current_servers = self.get_dns_servers()
        
        # Check if already exists
        if server in current_servers:
            self.logger.info(f"DNS server {server} already exists")
            return True
        
        # Add the new server
        current_servers.append(server)
        
        # Write back to file
        return self.set_dns_servers(current_servers)
    
    def remove_dns_server(self, server: str) -> bool:
        """
        Remove a single DNS server from the configuration.
        
        Args:
            server: DNS server IP address to remove
        
        Returns:
            True if successful, False otherwise
        """
        # Get current servers
        current_servers = self.get_dns_servers()
        
        # Check if exists
        if server not in current_servers:
            self.logger.warning(f"DNS server {server} not found in configuration")
            return False
        
        # Remove the server
        current_servers.remove(server)
        
        # Write back to file
        return self.set_dns_servers(current_servers)
    
    def validate_dns_ip(self, ip: str) -> bool:
        """
        Validate DNS server IP address format.
        
        Args:
            ip: IP address string to validate
        
        Returns:
            True if valid IPv4 address, False otherwise
        """
        return validate_ip_address(ip)
